tasks:
  - name: Install Foundry
    before: |
      docker-compose -f "./data/Data/modules/bitd-alternate-sheets/docker-compose.yml" pull
      docker-compose -f "./data/Data/modules/bitd-alternate-sheets/docker-compose.yml" up -d
checkoutLocation: "./data/Data/modules/bitd-alternate-sheets"
workspaceLocation: "/workspace"

additionalRepositories:
  - url: https://github.com/megastruktur/foundryvtt-blades-in-the-dark.git
    checkoutLocation: "./data/Data/systems/blades-in-the-dark"