tasks:
  - name: Install Foundry
    before: |
      mkdir data
    # docker-compose pull
    # docker-compose up -d
checkoutLocation: "./module"

additionalRepositories:
  - url: https://github.com/megastruktur/foundryvtt-blades-in-the-dark.git
    checkoutLocation: "./system"